### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by TheDutchCoder** [camsong/fetch-jsonp#36]
I tried installing this package as I need it to make calls to the Instagram API, but on an `npm install` I get the following errors:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node',
1 verbose cli   '/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--save',
1 verbose cli   'fetch-jsonp' ]
2 info using npm@5.0.0
3 info using node@v4.8.2
4 silly install loadCurrentTree
5 silly install readLocalPackageData
6 http fetch GET 200 https://registry.npmjs.org/fetch-jsonp 232ms
7 silly pacote range manifest for fetch-jsonp@^1.0.6 fetched in 270ms
8 silly install loadIdealTree
9 silly install cloneCurrentTreeToIdealTree
10 silly install loadShrinkwrap
11 verbose stack SyntaxError: Unexpected token <
11 verbose stack     at Object.parse (native)
11 verbose stack     at module.exports (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/utils/parse-json.js:3:15)
11 verbose stack     at /Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/lib/install/read-shrinkwrap.js:31:20
11 verbose stack     at tryCatcher (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/util.js:16:23)
11 verbose stack     at Holder$3._callFunction (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:14:44)
11 verbose stack     at Holder$3.checkFulfillment (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:29:30)
11 verbose stack     at Promise.eval (eval at <anonymous> (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/join.js:1:0), <anonymous>:6:20)
11 verbose stack     at Promise._settlePromise (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:566:21)
11 verbose stack     at Promise._settlePromise0 (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at Promise._settlePromise (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:582:21)
11 verbose stack     at Promise._settlePromise0 (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:614:10)
11 verbose stack     at Promise._settlePromises (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:693:18)
11 verbose stack     at Promise._fulfill (/Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/promise.js:638:18)
11 verbose stack     at /Users/reinierkaper/.nvm/versions/node/v4.8.2/lib/node_modules/npm/node_modules/bluebird/js/release/nodeback.js:42:21
12 verbose cwd /Users/reinierkaper/projects/docker/canvaspop
13 verbose Darwin 16.6.0
14 verbose argv "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/node" "/Users/reinierkaper/.nvm/versions/node/v4.8.2/bin/npm" "install" "--save" "fetch-jsonp"
15 verbose node v4.8.2
16 verbose npm  v5.0.0
17 error Unexpected token <
18 verbose exit [ 1, true ]
```

Any help would be appreciated.

**Comment by TheDutchCoder** [comment]
Apparently I get this on all packages, must be an npm issue
